spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: rikser-security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: rikser-security
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "rikser-security"
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: rikser-security
    liquibase-schema: rikser-security
    drop-first: false
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8081

jwt:
  expirationTime: ${EXPIRATION_TIME}
  secret: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

scheduler:
  clear-black-list:
    cron: "0 0 * * * *"

security:
  enabled: true
  service:
    enabled: false
    url: http://localhost:8081


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          down: 503