spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rikser-security
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true
  cloud:
    compatibility-verifier:
      enabled: false

jwt:
  expirationTime: 3600000
  refreshExpirationTime: 2592000000
  privateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdndJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLa3dnZ1NsQWdFQUFvSUJBUUR3bDlMWDUxMTFPdGhZDQpqVFprM2VGK2trQzMydzR5QXpQOGdndnVCYWRCS2VtaDRrQ0ZrZU1rUkRYNDZiY1hpT09jNjMwL1hxcSsxVnl0DQpERnMvSnBSaTZVTm9nY1pHaXFnRW00UkZXMzdWRTJWTitNd08xRWRWcFgzejdXNTd4TUxlc3RobkpZTlRWNlBHDQp1SzJWYVpSQ01UY2p2Z3ZEQlc4cVBxNEROc2RLR3ErS2JpYzIxQ2drdU5zQXlhTjB4amhRcTlLT1BkcGlEL09zDQoxelN5TEw0Wi9sL0M5TlB0NVdNdTMzbUJuK1RXUmdKZ3Q5WnI5bVJoamdHS3ZBK0tkTEE2OTJGRGN3dEZRTDQ2DQprVXdhejVWKzNnalRiZ01tT2JoUmFzRTJzUk9mN21FK0l0MC9DVVZseXZFaXBIZUJnS21YN1dqOWg0MHVjQmVZDQphT3o5U2hKaEFnTUJBQUVDZ2dFQUY5Qi9YejJZZzUwU2d4bGZNL2ErZGovVnhoMFp0NXVYanJ2MG9GZlE2V05UDQpxK0Z3VDRoVU9tZkNDK1JlYWliem1MbTZpUVkrMG1yZUpJYmZsVTJsVEhFWWFnVEdjbjhSQ0h1NFNRRTRlYkRVDQp5ellBUk11QVVCcjBiNnVsenZ4MzZZRThhR0ZQTVhXd1VXQkFWbFRBQnhsR0F2U3h4MWtIV3VBZmExUUZ2L0RaDQpJcEF0WFNVQ05mc2xSOHVEbGVEM1VhNFF4UDgwWFJydXFTVWxNZnM4UnlZUjJSZllZWGJxMGIzQmE4eEptQ3NLDQpHTU5MME0xQjgwQjRZMXpVNEw1WjZyZFNTSVhFeG8vYit6dnVJdEVwaWNlWUd4UnQxcUM5UTBLUklFK0dxby9GDQpHdVlHaERVMkQrQnR2SU9DK0JzV1JqSzRjcFh2UWlEOVg5OVRDbFF1VFFLQmdRRDdyRjRqQUFuelVqY0pwUFNkDQpOU2FneXVualFVOC9Bd2tMdE5tNmU3emExcWgzdHIwUi85akFsRUttYlBoN0hvQ1ltZ0MwaUNFd0hjMVo0MWNEDQpQZUxKVjFTUHJNbUEySmxHdG5hS1R5eHFTTXR3ckg4U3ZLcVpFeTFKcmVyc3ZtN0l4VFllaHJTZlBYVkE2RXplDQpWVmw3MldUZDJWN2RBRVNnMmIzLzRMbDZJd0tCZ1FEMHVyRGZhOXFIdkZDRWZHL25YMTZxb3dZNmVlSE9kdG50DQpTeEdOQ0NFYnVGN25mU0tXSFBXeUZrN2dySHRSRXhxdTlyQUJrTUpac2dsY1owd1krOUdIMGFHWWFYbDJYU2pPDQprYVRkWS9SekhiZnBZWVAvQXZoMFhiTURlaEZlekJlTEczaFBxUkdyTkphcElIRytYTHIrZnNLdjh0cVlsQ0kvDQp2UEZ6ZFl2ZnF3S0JnUUQ1L01zOUpPcTlZU3IrVDNZVE9ocDJtVmdkdmwvRERYYk14QVdKOFNNMGxRaWVjVXY1DQpOeFBNcHZoVmErU2VGenhSV0pmZXUyR0w4KzVvblNOdk91ZXNheXk1MGo0TjJCallYcUg4M0l3WHZ0c2x2cEl5DQp3R2tNeURteCtDbGtvL3hUUFdGMmpRT1pNV2pvNGxhSWVtcjZWSVNXd1RZemUvS3ZlOW40OHZZSjFRS0JnUURhDQpCcUNneXlOckhkZlYwRTZab0p0a0Jjejh0NnoyRldoZFFTMm5xWUJsZzhINUZjQ0VYOVI4RGVmRHZhWTNPbi9oDQpOQ0RscENPaGFUMXh0dzFTakxYRS9IdXNudnI0K2xIcWhsS01jZ3BMckVRMmhRdmxXcTRpYlgrWUwxM2VTSkVJDQorellhTWhOdHBYSTd4bzNPL0NvVHBMYXByZ0FWUXBPb21SbTZ0UlFoOVFLQmdRREdKaitnaU1NY3BqQXYyVUN6DQoyK084SHlQR1ltdkFoT3lVbUI2WnFMK3NFY2phVkU5K1RBSGI5d2c5enZsMWM3YkRsYmN5Z25sWSt5ekQrN2loDQpueVZYc1JwbFEvbFNqVkE0NlR5MW4vOWppY3Q4L3hPeTFMUUVWUTdwWWQrZFJBalh4YnRyQmRDcEM4ZlRTejY4DQppK2FEVEJ5ejFwSzdWMDVsdy9xbE0wV2dvQT09DQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tDQo=
  publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBOEpmUzErZGRkVHJZV0kwMlpOM2gNCmZwSkF0OXNPTWdNei9JSUw3Z1duUVNucG9lSkFoWkhqSkVRMStPbTNGNGpqbk90OVAxNnF2dFZjclF4YlB5YVUNCll1bERhSUhHUm9xb0JKdUVSVnQrMVJObFRmak1EdFJIVmFWOTgrMXVlOFRDM3JMWVp5V0RVMWVqeHJpdGxXbVUNClFqRTNJNzRMd3dWdktqNnVBemJIU2hxdmltNG5OdFFvSkxqYkFNbWpkTVk0VUt2U2pqM2FZZy96ck5jMHNpeSsNCkdmNWZ3dlRUN2VWakx0OTVnWi9rMWtZQ1lMZldhL1prWVk0Qmlyd1BpblN3T3ZkaFEzTUxSVUMrT3BGTUdzK1YNCmZ0NEkwMjRESmptNFVXckJOckVUbis1aFBpTGRQd2xGWmNyeElxUjNnWUNwbCsxby9ZZU5MbkFYbUdqcy9Vb1MNCllRSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg==

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

bundle:
  security:
    enabled: true
    service:
      enabled: false
      url: http://localhost:8081