spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: rikser-security
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true

jwt:
  expirationTime: 86400000
  secret: rikser123_aifhAISDdiO8198Lxkcn

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false